[package]
name = "atari"
version = "0.1.0"
authors = ["Igor Rzegocki <igor@rzegocki.pl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
